# Generated by Django 4.2.1 on 2023-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='answer',
            field=models.TextField(default='dummy'),
        ),
    ]
