# Generated by Django 4.2.1 on 2023-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_api', '0002_chats_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_headers', models.TextField(default='NOTHING')),
                ('ip_address', models.TextField(default='>>>')),
                ('other_information', models.TextField(default='NOTHING')),
            ],
        ),
    ]
